In [1]:
!pip install numpy


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np
#help(np)

In [34]:
#lst = [10,20,30,40,50]
lst = list(range(10,51,10))
print(lst,type(lst))

# convert list into ndarray
arr1 = np.array(lst)
print(arr1)
print(type(arr1))
print(arr1.shape) # tuple
print(arr1.ndim)
print(arr1.dtype) # 64 bits : 8 bytes
print(arr1.sum())
print(arr1.min())
print(arr1.max())

[10, 20, 30, 40, 50] <class 'list'>
[10 20 30 40 50]
<class 'numpy.ndarray'>
(5,)
1
int64
150
10
50


In [44]:
lst1 = [[10,20,30],[40,50,60]]
print(lst1,type(lst1))

# convert list into ndarray
#arr2 = np.array(lst1,dtype='i1')
arr2 = np.array(lst1,dtype= np.int8)

print(arr2)
print(type(arr2))
print(arr2.shape) # tuple
print(arr2.ndim)
print(arr2.dtype)
print("Sum of all the elements :",arr2.sum())
print("Sum of all the elements :",arr2.sum(axis=0))
print("Sum of all the elements :",arr2.sum(axis=1))
help(arr2.sum)
#help(np.sum)

[[10, 20, 30], [40, 50, 60]] <class 'list'>
[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>
(2, 3)
2
int8
Sum of all the elements : 210
Sum of all the elements : [50 70 90]
Sum of all the elements : [ 60 150]
Help on built-in function sum:

sum(...) method of numpy.ndarray instance
    a.sum(axis=None, dtype=None, out=None, keepdims=False, initial=0, where=True)

    Return the sum of the array elements over the given axis.

    Refer to `numpy.sum` for full documentation.

    See Also
    --------
    numpy.sum : equivalent function



In [22]:
lst = [10,20,3.2]
print(lst,type(lst))

[10, 20, 3.2] <class 'list'>


In [25]:
arr2 = np.array(lst)
print(arr2,type(arr2))
print(arr2.dtype)

[10.  20.   3.2] <class 'numpy.ndarray'>
float64


In [27]:
lst = [10,20,3.4,'welcome']
print(lst,type(lst))

[10, 20, 3.4, 'welcome'] <class 'list'>


In [30]:
arr3 = np.array(lst)
print(arr3,type(arr3))
print(arr3.dtype)

['10' '20' '3.4' 'welcome'] <class 'numpy.ndarray'>
<U32


In [47]:
#for name in dir(arr3):
#for name in dir(np):
#    if '_' not in name:
#        print(name)

In [58]:
# create ndarray with all the 1s
#help(np.ones)
arr1 = np.ones(2)
print(arr1,type(arr1))

arr2 = np.ones((3,5))
print(arr2,type(arr2))

#arr2 = np.ones((3,5),dtype=np.float16)# 'f2'
arr2 = np.ones((3,5),dtype='f2')# 'f2'
print(arr2,type(arr2))
print(arr2.dtype)

[1. 1.] <class 'numpy.ndarray'>
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] <class 'numpy.ndarray'>
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] <class 'numpy.ndarray'>
float16


In [60]:
#help(np)