In [1]:
#indexing : Positive and Negative

import numpy as np

lst = list(range(10,101,10))
arr = np.array(lst)

print(arr)
print(arr[0]) # positive indexing
print(arr[2]) # positive indexing

print(arr[-1]) # negative indexing
print(arr[-4]) # negative indexing


[ 10  20  30  40  50  60  70  80  90 100]
10
30
100
70


In [5]:
# slicing  : Positive and Negative

import numpy as np

lst = list(range(10,101,10))
arr = np.array(lst)

print(arr)

# positive slicing
print(arr[0:2]) 
print(arr[5:])
print(arr[:4])
print(arr[::2])
print(arr[:5:2])

# negative slicing
print(arr[-5:]) 
print(arr[-5:-7])
print(arr[-5:-7:-1])
print(arr[::-1])


[ 10  20  30  40  50  60  70  80  90 100]
[10 20]
[ 60  70  80  90 100]
[10 20 30 40]
[10 30 50 70 90]
[10 30 50]
[ 60  70  80  90 100]
[]
[60 50]
[100  90  80  70  60  50  40  30  20  10]
