## Homogeneity
- All elements in a NumPy array must be of the same data type (e.g., all integers, all floats, etc.).
- This ensures efficient memory usage and consistent performance.

In [1]:
import numpy as np
arr = np.array([1, 2, 3])  # All elements are integers
print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.itemsize)

[1 2 3]
(3,)
int64
1
8


## Fixed Size
- The size of a NumPy array is fixed upon creation.
- You cannot add or remove elements directly; instead, you must create a new array if the size needs to change.

## Efficient Memory Usage
- NumPy arrays are stored in contiguous blocks of memory, making them faster and more memory-efficient than Python lists.

## Support for Multi-Dimensional Data
- Arrays can have multiple dimensions (1D, 2D, 3D, or higher):
- 1D array: [1, 2, 3]
- 2D array: [[1, 2], [3, 4]]
- 3D array: [[[1], [2]], [[3], [4]]]

## Broadcasting
- NumPy supports broadcasting, allowing arithmetic operations between arrays of different shapes (if they are compatible).

In [2]:
arr1 = np.array([1, 2, 3])
arr2 = 2
print(arr1 + arr2)  # Output: [3 4 5]


[3 4 5]


## Immutability of Data Type
- Once an array is created, its data type (dtype) cannot be changed. However, you can create a new array with a different type by casting:

In [4]:
arr = np.array([1, 2, 3], dtype=int)
print(id(arr))
print(arr)
arr_float = arr.astype(float)  # Cast to float
print(id(arr_float))
print(arr_float)

1566901584880
[1 2 3]
1566901584400
[1. 2. 3.]


## Indexing and Slicing
- NumPy arrays support advanced indexing and slicing, including boolean indexing.

In [5]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])  # Output: [20 30 40]
print(arr[arr > 25])  # Output: [30 40 50] # boolean indexing


[20 30 40]
[30 40 50]


## Performance
- NumPy is highly optimized for numerical operations and is much faster than Python lists due to its implementation in C.

In [6]:
arr = np.array([1, 2, 3])
print(arr * 2)  # Element-wise operation: [2 4 6]


[2 4 6]


## Universal Functions (UFuncs)
- NumPy provides built-in mathematical functions (sin, cos, log, etc.) that operate element-wise on arrays.

In [7]:
arr = np.array([0, np.pi/2, np.pi])
print(np.sin(arr))  # Output: [0. 1. 0.]

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


## Shape and Dimension
- Each array has a shape and dimension:
- shape: Tuple representing the size of each dimension.
- ndim: Number of dimensions.

In [8]:
arr = np.array([[1, 2], [3, 4]])
print(arr.shape)  # Output: (2, 2)
print(arr.ndim)   # Output: 2

(2, 2)
2


## Mutable Elements
- You can modify individual elements or slices of an array

In [9]:
arr = np.array([1, 2, 3])
arr[0] = 10
print(arr)  # Output: [10 2 3]


[10  2  3]
